### ISSUE TITLE
Outline of notebook sections

### ISSUE THREAD

**Issue by ymma98** [EverettYou/Mathematica-for-physics#3]
It would be nice to add a navigation box to show the outline of sections when the article is long. How about integrating this function to CMU article style sheet?

**Comment by EverettYou** [comment]
Nice suggestions. I found a relevant discussion on StackExchange: https://mathematica.stackexchange.com/questions/132467/outline-of-notebook-sections

I do not have a plan to implement it yet.

I normally collapse the cells to the subsection level, then it automatically looks like a nice and clean outline. I can expand specific subsections to read or write and collapse them when I finish. In this way, I do not have to see all the content in a long article.
